{% set name = "pythonanywhere" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27d0111acb70ae751bf117a451d4a4826ae3fe1ac221b0e1c3a0044bf7621172

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - docopt
    - packaging
    - python-dateutil
    - requests
    - schema
    - tabulate
    - typer

test:
  imports:
    - cli
    - pythonanywhere
    - pythonanywhere.api
  requires:
    - pip
  commands:
    - pip check
    - pa --help

about:
  home: https://github.com/pythonanywhere/helper_scripts/
  summary: PythonAnywhere helper tools for users
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/pythonanywhere/helper_scripts/blob/master/LICENSE
  dev_url: https://github.com/pythonanywhere/helper_scripts/
  doc_url: https://github.com/pythonanywhere/helper_scripts/blob/master/README.md

extra:
  recipe-maintainers:
    - bkreider
    - skupr-anaconda