{% set name = "pythonanywhere" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - pa = cli.pa:app

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c8098c9670f4efb89620a7b7915f78a591248711aa2bc18082aa8fc76fcd19de
  - url: https://github.com/{{ name }}/helper_scripts/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6ca250d3e5d5ecfa1837b0fa73e3cd7959ca4f8e43619c396effec0c7fc30fd7
    folder: gh_src

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - docopt
    - packaging
    - python-dateutil
    - pythonanywhere-core ==0.2.9
    - requests
    - schema
    - snakesay ==0.10.4
    - tabulate
    - typer

# tests/test_scripts_commons.py:34: AssertionError
# "Key '--toggle' error: (None, <class 'bool'>) did not validate 'not valid value'"
{% set SKIP_TEST_POSIX = [
    "test_validates_hours",
    "test_validates_minutes",
    "test_validates_log_number",
    "test_warns_when_wrong_format_provided",
    "test_validates_minute",
    "test_validates_hour",
    "test_exits_because_boolean_not_satisfied"
] %}

# Multiple AssertionError mostly regarding win path issue
{% set SKIP_TEST_WIN64 = [
    "test_creates_pa_path_with_provided_path",
    "test_exits_with_success_when_successful_upload",
    "test_exits_with_error_when_unsuccessful_upload",
    "test_create_calls_all_stuff_in_right_order",
    "test_raises_if_multiple_branches",
    "test_deletes_directory_if_branch_does_not_exist",
    "test_program_raises_if_branch_does_not_exist",
    "test_deletes_directory_if_multiple_branches",
    "test_creates_folder",
    "test_calls_startproject_for_older_django",
    "test_calls_startproject_for_newer_django",
    "test_if_requirements_txt_exists",
    "test_nuke_option_deletes_directory_first",
    "test_project_path",
    "test_exits_because_boolean_not_satisfied",
    "test_nuke_option_overrides_directory_checks",
    "test_raises_if_project_path_exists",
    "test_validates_hours",
    "test_validates_minutes",
    "test_validates_log_number",
    "test_warns_when_wrong_format_provided",
    "test_validates_minute",
    "test_validates_hour",
    "test_calls_git_subprocess",
    "test_nuke_option_ignores_directory_doesnt_exist",
    "test_checks_happy_path_with_one_branch",
    "test_checks_if_branch_exists",
    "test_nuke_option_handles_directory_not_existing",
    "test_project_domain_and_python_version",
    "test_checkouts_branch_if_not_current_head",
    "test_runs_manage_py_in_correct_virtualenv",
    "test_project_wsgi_file_path",
    "test_does_not_checkouts_branch_if_current_head",
    "test_runs_manage_py_in_correct_virtualenv",
    "test_project_webapp",
    "test_is_versionless_django_by_default",
    "test_project_virtualenv",
    "test_sanity_checks_raises_if_virtualenv_exists",
    "test_sanity_checks_calls_webapp_sanity_checks",
    "test_start_bash_calls_launch_bash_in_virtualenv_with_virtualenv_and_project_path",
    "test_sanity_checks_raises_if_project_path_exists",
    "test_start_bash_calls_launch_bash_in_virtualenv_with_unique_id",
    "test_sanity_checks_nuke_option_overrides_directory_checks"
] %}

test:
  source_files:
    - gh_src/tests
    - gh_src/scripts
  imports:
    - cli
    - cli.django
    - cli.pa
    - cli.path
    - cli.schedule
    - cli.students
    - cli.webapp
    - cli.website
    - pythonanywhere
    - pythonanywhere.django_project
    - pythonanywhere.exceptions
    - pythonanywhere.files
    - pythonanywhere.launch_bash_in_virtualenv
    - pythonanywhere.project
    - pythonanywhere.scripts_commons
    - pythonanywhere.students
    - pythonanywhere.task
    - pythonanywhere.utils
    - pythonanywhere.virtualenvs
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-xdist
    - psutil
    - responses
  commands:
    - pip check
    - pa --help
    - pytest -n auto -m "not slowtest" -v --color=yes gh_src/tests -k "not ({{ SKIP_TEST_POSIX | join(' or ') }})"  # [not win]
    - pytest -n auto -m "not slowtest" -v --color=yes gh_src/tests -k "not ({{ SKIP_TEST_WIN64 | join(' or ') }})"  # [win]

about:
  home: https://github.com/pythonanywhere/helper_scripts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
  summary: PythonAnywhere helper tools for users
    PythonAnywhere is a collection of helper scripts and command-line tools 
    for interacting with the PythonAnywhere cloud platform. It allows users to manage files, 
    databases, web apps, scheduled tasks, and virtual environments directly 
    from their local terminal.
  dev_url: https://github.com/pythonanywhere/helper_scripts
  doc_url: https://github.com/pythonanywhere/helper_scripts/blob/master/README.md

extra:
  recipe-maintainers:
    - bkreider
    - skupr-anaconda